spring.application.name=esprit-market

# ===== Database =====
spring.datasource.url=jdbc:mysql://localhost:3306/esprit_market?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===== Server =====
server.port=8081

# ===== JWT Security =====
# Secret key (Keep it safe!)
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Token expiration in ms (86400000 = 24 hours)
jwt.expiration=86400000
# ===== Mailtrap Configuration (Email Service) =====
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=9dab7c9d99f91d
spring.mail.password=8e678afbb6dd09
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===== Social Login (OAuth2) =====
# Google: Get from https://console.cloud.google.com → APIs & Services → Credentials
google.client.id=657824293337-88tekq3h4p524uo1npselrhlv72k8v7a.apps.googleusercontent.com

